# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "kvm-test";

  # Host-specific system packages
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
  ];

  # Bootloader
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/vda";
  boot.loader.grub.useOSProber = true;

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "25.11";
}
