general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock after 10 min idle
listener {
    timeout = 600
    cmd = hyprlock
}

# Screens off after 30 min idle
listener {
    timeout = 1800
    cmd = hyprctl dispatch dpms off
}

# Suspend after 30 min idle
listener {
    timeout = 1800
    cmd = systemctl suspend
}