# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    ../../modules/core/gpu/nvidia.nix
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "nixos-workstation";

  workstation = {
    hyprland.enable = true;
  };

	services.displayManager.sddm = {
    enable =true;
    wayland.enable = true;
  };

  # Host-specific system packages
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
	  vscode
  ];

  boot = {
    loader = {
      efi.canTouchEfiVariables = true;
      grub = {
        enable = true;
        useOSProber = true;
        devices = [ "nodev" ];
        efiSupport = true;

        theme = ./tsushima;
        configurationLimit = 5;  # max 5 versions in bootloader
      };
    };
  };

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05";
}
