# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    ../../modules/core/gpu/nvidia.nix
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "nixos-workstation";

  myDesktop.gnome.enable = false;
  myDesktop.hyprland.enable = true;

  # Host-specific system packages
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
	  vscode
  ];

  boot.loader.grub.theme = ./tsushima;

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05";
}
