# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "benjidev-nixos";

  # Host-specific system packages
  environment.systemPackages = with pkgs; [

  ];

  boot.loader.grub.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.loader.grub.useOSProber = true;
  boot.loader.grub.devices = [ "nodev" ];
  boot.loader.grub.efiSupport = true;

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "25.11";
}
