background=/home/benjidev/Pictures/Wallpapers/default.jpg

preload = /home/benjidev/Pictures/Wallpapers/default.jpg

wallpaper = DP-1,/home/benjidev/Pictures/Wallpapers/default.jpg
wallpaper = HDMI-A-1,/home/benjidev/Pictures/Wallpapers/default.jpg

ipc = on
