wallpaper {
    monitor = DP-5
    path = /home/benjidev/Pictures/Wallpapers/default.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-5
    path = /home/benjidev/Pictures/Wallpapers/default.jpg
    fit_mode = cover
}

splash = false
ipc = on
