-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local mainMod = "SUPER"

local terminal = "kitty"

hl.config({
    animations = {
        enabled = true,
    },
})

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("fuzzel"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("cliphist list| fuzzel --dmenu --with-nth 2| cliphist decode| wl-copy"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "Escape", hl.dsp.exec_cmd("hyprlock"))

hl.bind("Print", hl.dsp.exec_cmd("hyprshot -m output --clipboard-only"))

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("hyprshot -m window --clipboard-only"))

hl.bind(mainMod .. " + " .. "h", hl.dsp.layout("focus l"))

hl.bind(mainMod .. " + " .. "l", hl.dsp.layout("focus r"))

hl.bind(mainMod .. " + " .. "k", hl.dsp.layout("focus u"))

hl.bind(mainMod .. " + " .. "j", hl.dsp.layout("focus d"))

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "ALT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "up", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "h", hl.dsp.layout("swapcol l"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "l", hl.dsp.layout("swapcol r"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "k", hl.dsp.layout("consume"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "j", hl.dsp.layout("expel"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "h", hl.dsp.layout("colresize -conf"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "l", hl.dsp.layout("colresize +conf"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "k", hl.dsp.layout("colresize -0.05"))

hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "j", hl.dsp.layout("colresize +0.05"))

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.config({
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
            size = 4,
        },
        shadow = {
            color = "rgba(1e1e2e99)",
        },
        rounding = 10,
    },
})





hl.config({
    general = {
        border_size = 2,
        gaps_in = 5,
        gaps_out = 10,
        layout = "scrolling",
        col = {
            active_border = "rgb(89b4fa)",
            inactive_border = "rgb(6c7086)",
        },
    },
})

hl.config({
    group = {
        groupbar = {
            col.active = "rgb(89b4fa)",
            col.inactive = "rgb(6c7086)",
            text_color = "rgb(cdd6f4)",
        },
        col = {
            border_active = "rgb(89b4fa)",
            border_inactive = "rgb(6c7086)",
            border_locked_active = "rgb(94e2d5)",
        },
    },
})

hl.config({
    input = {
        follow_mouse = 2,
        kb_layout = "us",
        kb_options = "caps:super",
        sensitivity = 0,
    },
})

hl.config({
    misc = {
        background_color = "rgb(1e1e2e)",
    },
})

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
