# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    users.<username>
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "<hostname>";

  # Host-specific system packages
  environment.systemPackages = with pkgs; [

  ];

  boot.loader.grub.theme = ./THEME_FOLDER

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05"; # CHANGE THIS TO MATCH YOUR NIXOS VERSION
}
