# Host configuration template

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    users.<username>
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "<hostname>";

  # Host-specific system packages
  environment.systemPackages = with pkgs; [

  ];

  boot.loader.grub = {
    enable = true;
    efi.canTouchEfiVariables = true;
    grub = {
      useOSProber = true;
      devices = [ "nodev" ];
      efiSupport = true;
    }
  };

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05"; # CHANGE THIS TO MATCH YOUR NIXOS VERSION
}
