# Host configuration template.

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../profiles/core.nix       # Shared between every device
    # ../../profiles/desktop.nix  # For an interactive desktop machine (Hyprland, etc.)
    # For a headless server: keep core, and define the server stack (SSH,
    # firewall, containers) directly in this file — see hosts/argon.
    # users.benjidev              # Primary user account (desktop hosts only):
    #                             # import it here, NOT in the desktop profile.
    # ../../modules/services/monitoring  # Prometheus monitoring. On a new
    #                             # server enable:
    #                             #   services.monitoring.exporter.enable = true;
    #                             # and add its tailnet name to the hub host's
    #                             # services.monitoring.server.targets (see argon).
    # ../../modules/services/dashboard    # Services landing page (Homepage module)
    #                             # behind nginx on port 80. Define
    #                             # services.dashboard = { enable = true;
    #                             #   services = [ ... ]; } — each service can
    #                             # point at any IP/hostname; non-web services
    #                             # get an /info/<slug> page via `info`.
  ];

  # Global options (allowUnfree, flake settings, ...) come from the core profile.

  networking.hostName = "<hostname>";

  # Primary desktop user — pick a name (defaults to "benjidev"); the desktop
  # persona and the user module follow this instead of hardcoding one.
  # workstation.user = "benjidev";

  # Host-specific GPU driver (pick one — each pulls in the base graphics stack):
  # imports = [ ../../modules/core/gpu/amd.nix ];    # AMD
  # imports = [ ../../modules/core/gpu/nvidia.nix ]; # NVIDIA

  # Host-specific system packages
  environment.systemPackages = with pkgs; [

  ];

  # Host-specific bootloader (pick one):
  # boot.loader.grub.theme = ./THEME_FOLDER
  # boot.loader.systemd-boot.enable = true;

# For a desktop host, host-specific display bits go in the host file:
#   - Hyprland monitors/workspaces in a host.lua (see hosts/radon/hyprland-host.lua)
#     installed via:
#       home-manager.users.<user>.xdg.configFile."hypr/host.lua".source = ./hyprland-host.lua;
#   - Noctalia wallpaper + desktop widgets
#     (see hosts/radon/default.nix — the desktop profile keeps these out of the
#     shared layer). The lock screen is hyprlock everywhere (hypridle locks
#     after idling; qylock is only the SDDM login theme).

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05"; # CHANGE THIS TO MATCH YOUR NIXOS VERSION
}