# Host configuration template.

{ config, pkgs, inputs, users, ... }: {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../profiles/core.nix       # Shared between every device
    # ../../profiles/desktop.nix  # For an interactive desktop machine (Hyprland, etc.)
    # For a headless server: keep core, and define the server stack (SSH,
    # firewall, containers) directly in this file — see hosts/argon.
  ];

  # Global options (allowUnfree, flake settings, ...) come from the core profile.

  networking.hostName = "<hostname>";

  # Host-specific GPU driver (pick one):
  # imports = [ ../../modules/core/gpu/amd.nix ];    # AMD
  # imports = [ ../../modules/core/gpu/nvidia.nix ]; # NVIDIA

  # Host-specific system packages
  environment.systemPackages = with pkgs; [

  ];

  # Host-specific bootloader (pick one):
  # boot.loader.grub.theme = ./THEME_FOLDER
  # boot.loader.systemd-boot.enable = true;

  # For a desktop host, host-specific Hyprland monitors/keybinds go in:
  #   home-manager.users.<user>.wayland.windowManager.hyprland.settings = { ... };

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05"; # CHANGE THIS TO MATCH YOUR NIXOS VERSION
}
