# Host configuration template

{ config, lib, pkgs, inputs, users, ... }:
let
  # SDDM's greeter runs inside weston (kiosk shell), which shows the login screen
  # on its "primary" output - that can land on the secondary monitor (HDMI-A-1).
  # Pin the greeter app to DP-1 via weston's per-output app-ids instead.
  westonIni = (pkgs.formats.ini { }).generate "weston.ini" {
    libinput = {
      enable-tap = config.services.libinput.mouse.tapping;
      left-handed = config.services.libinput.mouse.leftHanded;
    };
    keyboard = {
      keymap_model = config.services.xserver.xkb.model;
      keymap_layout = config.services.xserver.xkb.layout;
      keymap_variant = config.services.xserver.xkb.variant;
      keymap_options = config.services.xserver.xkb.options;
    };
    output = {
      name = "DP-1";
      app-ids = "sddm-greeter-qt6";
    };
  };
in {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    ../../modules/core/gpu/nvidia.nix
    inputs.silentSDDM.nixosModules.default
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "radon";

  # Auto-mount data drives (mounted by systemd at boot; nofail = won't block boot if absent)
  fileSystems."/mnt/games" = {
    device = "/dev/disk/by-uuid/9f0c7685-7d74-496d-94a1-f5fd7e6e21db"; # sdb1 ext4 "Games"
    fsType = "ext4";
    options = [ "nofail" "noatime" ];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/5652DA3D52DA2213"; # sda3 ntfs "Basic data partition"
    fsType = "ntfs3";
    options = [ "nofail" "x-systemd.device-timeout=5" "ro" "uid=1000" "gid=100" "fmask=0111" "dmask=000" ];
  };

  fileSystems."/mnt/zorin" = {
    device = "/dev/disk/by-uuid/3d97e9d6-17f8-46b9-ab8c-c9f5acf2a2d2"; # nvme0n1p1 ext4 (Zorin OS)
    fsType = "ext4";
    options = [ "nofail" "ro" "noatime" ]; # read-only so NixOS never writes to Zorin's root
  };

  workstation = {
    hyprland.enable = true;
    gaming.enable = true;
  };

	programs.silentSDDM = {
    enable = true;
    theme = "catppuccin-mocha";
  };

  services.displayManager.sddm.wayland.compositorCommand =
    "${pkgs.weston}/bin/weston --shell=kiosk -c ${westonIni}";

  # Host-specific system packages
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
	  vscode
  ];

  boot = {
    loader = {
      efi.canTouchEfiVariables = true;
      grub = {
        enable = true;
        useOSProber = true;
        devices = [ "nodev" ];
        efiSupport = true;

        theme = ./tsushima;
        configurationLimit = 5;  # max 5 versions in bootloader
      };
    };
  };

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05";
}
