# Host configuration template

{ config, pkgs, inputs, users, ... }:
let
  sddmTheme = pkgs.sddm-astronaut.overrideAttrs (old: {
      installPhase = old.installPhase + ''
        chmod -R u+w $out/share/sddm/themes/sddm-astronaut-theme
        cp ${./sddm/astronaut.conf} $out/share/sddm/themes/sddm-astronaut-theme/Themes/astronaut.conf
      '';
  });
in {
  imports = [
    ./hardware-configuration.nix  # Generated by nixos-generate-config
    ../../modules                 # Shared modules
    ../../modules/core/gpu/nvidia.nix
    users.benjidev
  ];

  nixpkgs.config.allowUnfree = true;

  networking.hostName = "radon";

  workstation = {
    hyprland.enable = true;
  };

	services.displayManager.sddm = {
    enable = true;
    wayland.enable = true;
    theme = "sddm-astronaut-theme";
    extraPackages = [ sddmTheme ];
  };

  # Host-specific system packages
  environment.systemPackages = with pkgs; [
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
	  vscode
    sddmTheme
  ];

  boot = {
    loader = {
      efi.canTouchEfiVariables = true;
      grub = {
        enable = true;
        useOSProber = true;
        devices = [ "nodev" ];
        efiSupport = true;

        theme = ./tsushima;
        configurationLimit = 5;  # max 5 versions in bootloader
      };
    };
  };

  # System state version - DO NOT CHANGE this after first install
  system.stateVersion = "26.05";
}
